<font size="+3">Duo Design CXCR4</font>

In [2]:
import glob
import os
import shutil
import csv
import os
import sys
import json

import json
import numpy as np
import pandas as pd

from Bio.PDB import PDBParser, PPBuilder, MMCIFParser, PDBIO 
import MDAnalysis as mda
from MDAnalysis.analysis import align
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="MDAnalysis")

# Sequences

In [8]:
pdb_files = ['hCXCR4_af3_inactive.pdb', 'mCXCR4_af3_inactive.pdb']

for pdb_file in pdb_files:
    print(f"\n### {pdb_file}")
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("prot", pdb_file)

    seqs = {}

    for model in structure:
        for chain in model:
            seq = []
            for residue in chain:
                if Polypeptide.is_aa(residue, standard=True):
                    seq.append(seq1(residue.resname))
            if seq:
                seqs[chain.id] = "".join(seq)

    for chain_id, sequence in seqs.items():
        print(f">chain_{chain_id}")
        print(sequence)

### hCXCR4_af3_inactive.pdb
>chain_A
FREENANFNKIFLPTIYSIIFLTGIVGNGLVILVMGYQKKLRSMTDKYRLHLSVADLLFVITLPFWAVDAVANWYFGNFLCKAVHVIYTVNLYSSVLILAFISLDRYLAIVHATNSQRPRKLLAEKVVYVGVWIPALLLTIPDFIFANVSEADDRYICDRFYPNDLWVVVFQFQHIMVGLILPGIVILSCYCIIISKLSHSKGHQKRKALKTTVILILAFFACWLPYYIGISIDSFILLEIIKQGCEFENTVHKWISITEALAFFHCCLNPILYAFLGAKFKTSAQHALTSVSRGSSLKILSKGKR

### mCXCR4_af3_inactive.pdb
>chain_A
FRDENVHFNRIFLPTIYFIIFLTGIVGNGLVILVMGYQKKLRSMTDKYRLHLSVADLLFVITLPFWAVDAMADWYFGKFLCKAVHIIYTVNLYSSVLILAFISLDRYLAIVHATNSQRPRKLLAEKAVYVGVWIPALLLTIPDFIFADVSQGDISQGDDRYICDRLYPDSLWMVVFQFQHIMVGLILPGIVILSCYCIIISKLSHSKGHQKRKALKTTVILILAFFACWLPYYVGISIDSFILLGVIKQGCDFESIVHKWISITEALAFFHCCLNPILYAFLGAKFKSSAQHALNSMSRGSSLKILSKGKR

# Sequence Identity

In [20]:
human = "FREENANFNKIFLPTIYSIIFLTGIVGNGLVILVMGYQKKLRSMTDKYRLHLSVADLLFVITLPFWAVDAVANWYFGNFLCKAVHVIYTVNLYSSVLILAFISLDRYLAIVHATNSQRPRKLLAEKVVYVGVWIPALLLTIPDFIFANVSEADDRYICDRFYPNDLWVVVFQFQHIMVGLILPGIVILSCYCIIISKLSHSKGHQKRKALKTTVILILAFFACWLPYYIGISIDSFILLEIIKQGCEFENTVHKWISITEALAFFHCCLNPILYAFLGAKFKTSAQHALTSVSRGSSLKILSKGKR"
mouse = "FRDENVHFNRIFLPTIYFIIFLTGIVGNGLVILVMGYQKKLRSMTDKYRLHLSVADLLFVITLPFWAVDAMADWYFGKFLCKAVHIIYTVNLYSSVLILAFISLDRYLAIVHATNSQRPRKLLAEKAVYVGVWIPALLLTIPDFIFADVSQGDISQGDDRYICDRLYPDSLWMVVFQFQHIMVGLILPGIVILSCYCIIISKLSHSKGHQKRKALKTTVILILAFFACWLPYYVGISIDSFILLGVIKQGCDFESIVHKWISITEALAFFHCCLNPILYAFLGAKFKSSAQHALNSMSRGSSLKILSKGKR"

# Perform global pairwise alignment
alignments = pairwise2.align.globalxx(human, mouse)

# Take the best alignment (highest score)
best_alignment = alignments[0]
aligned_human, aligned_mouse, score, start, end = best_alignment

# Calculate sequence identity
matches = sum(1 for a, b in zip(aligned_human, aligned_mouse) if a == b)
length = len(aligned_human)
seq_identity = (matches / length) * 100

print(f"Sequence Identity: {seq_identity:.2f}%")
print(f"Alignment length: {length}")

Sequence Identity: 83.63%
Alignment length: 336

# Remove Trajectories with Membrane Clashes

## Prepare References

In [4]:
def simple_rotation_matrix(a, b):
    a = a / np.linalg.norm(a)
    b = b / np.linalg.norm(b)
    v = np.cross(a, b)
    c = np.dot(a, b)
    K = np.array([
        [0, -v[2], v[1]],
        [v[2], 0, -v[0]],
        [-v[1], v[0], 0]
    ])
    return np.eye(3) + K + K @ K * (1 / (1 + c))

In [53]:
species = ['mouse', 'human']

for s in species:

    u = mda.Universe(f'{s[0]}CXCR4_short.pdb')
    sel = u.select_atoms('all')
    
    sel.translate(-sel.center_of_mass())
    
    # align principal axis with z
    principal_axis = sel.principal_axes()[2]
    principal_axis /= np.linalg.norm(principal_axis)

    if s == 'human':
        x = u.select_atoms("name CA and resid 167").center_of_mass()
        y = u.select_atoms("name CA and resid 178").center_of_mass()
    else:
        x = u.select_atoms("name CA and resid 172").center_of_mass()
        y = u.select_atoms("name CA and resid 183").center_of_mass()

    principal_axis = x-y
    principal_axis /= np.linalg.norm(principal_axis)

    z_axis = np.array([0, 0, 1])
    
    R = simple_rotation_matrix(principal_axis, z_axis)
    sel.rotate(R)
    
    sel.write(f'{s[0]}CXCR4_short.pdb')

## Align to References

In [ ]:
species = ['mouse', 'human']

outdir = 'Trajectory/Aligned'
os.makedirs(outdir, exist_ok=True)

for s in species:
    ref = mda.Universe(f'{s[0]}CXCR4_short.pdb')
    sel_ref = ref.select_atoms('chainID A')

    files = glob.glob(f'Trajectory/Relaxed/*_{s}.pdb')
    files.sort()

    for file in files:
        design = os.path.basename(file)
        u = mda.Universe(file) 
        sel_u = u.select_atoms('chainID A and not type H and not name OXT')

        align.alignto(u, ref, select='chainID A and not type H and not name OXT')
        sel = u.select_atoms('all')
        sel.write(f'{outdir}/{design}')

Trajectory/Relaxed/CXCR4_l100_s14635CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l100_s87186CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l101_s50501CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l102_s38852CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l103_s28173CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l103_s82425CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l105_s9788CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l106_s15325CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l106_s15564CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l106_s22762CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l106_s26386CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l106_s75775CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l107_s24933CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l107_s75675CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l107_s8342CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l107_s84555CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l108_s83259CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l110_s62526CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l110_s83184CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l111_s4194CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l112_s51646CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l113_s37544CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l113_s53451CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l113_s79432CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l113_s87864CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l114_s20005CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l114_s95097CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l115_s11981CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l116_s68332CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l116_s9124CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l117_s14292CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l117_s46290CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l118_s39379CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l118_s51250CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l118_s60515CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l119_s5870CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l120_s26368CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l120_s32630CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l121_s85675CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l122_s57564CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l123_s35355CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l123_s94967CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l124_s64368CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l125_s22072CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l126_s5675CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l127_s34160CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l127_s52757CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l128_s84702CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l130_s64914CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l132_s90785CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l133_s10180CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l133_s23417CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l133_s48643CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l134_s13755CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l134_s3769CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l134_s38147CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l136_s18439CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l136_s39129CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l137_s56033CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l137_s97919CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l138_s29893CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l138_s35938CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l139_s60898CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l140_s32153CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l142_s11162CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l142_s67503CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l142_s68181CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l143_s29399CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l143_s67712CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l144_s7262CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l145_s21099CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l145_s47467CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l145_s73233CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l146_s29253CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l149_s6361CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l149_s67589CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l149_s94187CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l151_s74375CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l153_s20768CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l153_s87346CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l153_s89532CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l155_s85163CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l160_s23897CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l160_s36808CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l160_s92625CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l161_s32811CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l161_s42654CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l161_s67752CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l162_s67110CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l163_s2059CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l163_s88851CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l164_s31992CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l165_s85964CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l166_s77096CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l166_s88823CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l169_s60830CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l171_s33268CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l172_s2873CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l172_s33942CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l172_s54197CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l172_s92959CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l172_s95662CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l173_s51114CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l174_s41447CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l174_s6023CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l174_s8954CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l176_s38200CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l176_s52627CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l176_s64546CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l176_s7220CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l176_s76716CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l178_s96856CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l179_s21760CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l179_s98276CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l180_s34582CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l181_s169CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l182_s17608CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l182_s33850CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l182_s48615CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l183_s75566CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l184_s36674CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l185_s81363CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l187_s56431CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l189_s42992CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l189_s66202CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l189_s76396CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l190_s57759CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l191_s98468CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l192_s11984CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l193_s29590CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l193_s97971CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l194_s31969CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l194_s35134CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l194_s67974CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l196_s18101CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l196_s40309CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l197_s49285CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l198_s34327CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l199_s5126CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l199_s78131CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l200_s22287CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l80_s25703CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l81_s37449CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l86_s13025CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l86_s20990CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l86_s34002CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l87_s95365CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l89_s17742CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l93_s72331CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l94_s47741CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l94_s96090CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l95_s17057CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l95_s28184CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l97_s31534CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l97_s880CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l98_s13450CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l99_s56553CXCR4_mouse.pdb
Trajectory/Relaxed/CXCR4_l100_s14635CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l100_s87186CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l101_s50501CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l102_s38852CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l103_s28173CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l103_s82425CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l105_s9788CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l106_s15325CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l106_s15564CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l106_s22762CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l106_s26386CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l106_s75775CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l107_s24933CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l107_s75675CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l107_s8342CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l107_s84555CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l108_s83259CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l110_s62526CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l110_s83184CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l111_s4194CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l112_s51646CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l113_s37544CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l113_s53451CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l113_s79432CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l113_s87864CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l114_s20005CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l114_s95097CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l115_s11981CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l116_s68332CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l116_s9124CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l117_s14292CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l117_s46290CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l118_s39379CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l118_s51250CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l118_s60515CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l119_s5870CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l120_s26368CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l120_s32630CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l121_s85675CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l122_s57564CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l123_s35355CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l123_s94967CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l124_s64368CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l125_s22072CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l126_s5675CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l127_s34160CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l127_s52757CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l128_s84702CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l130_s64914CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l132_s90785CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l133_s10180CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l133_s23417CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l133_s48643CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l134_s13755CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l134_s3769CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l134_s38147CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l136_s18439CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l136_s39129CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l137_s56033CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l137_s97919CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l138_s29893CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l138_s35938CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l139_s60898CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l140_s32153CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l142_s11162CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l142_s67503CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l142_s68181CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l143_s29399CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l143_s67712CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l144_s7262CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l145_s21099CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l145_s47467CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l145_s73233CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l146_s29253CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l149_s6361CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l149_s67589CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l149_s94187CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l151_s74375CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l153_s20768CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l153_s87346CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l153_s89532CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l155_s85163CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l160_s23897CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l160_s36808CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l160_s92625CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l161_s32811CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l161_s42654CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l161_s67752CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l162_s67110CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l163_s2059CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l163_s88851CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l164_s31992CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l165_s85964CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l166_s77096CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l166_s88823CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l169_s60830CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l171_s33268CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l172_s2873CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l172_s33942CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l172_s54197CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l172_s92959CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l172_s95662CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l173_s51114CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l174_s41447CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l174_s6023CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l174_s8954CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l176_s38200CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l176_s52627CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l176_s64546CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l176_s7220CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l176_s76716CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l178_s96856CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l179_s21760CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l179_s98276CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l180_s34582CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l181_s169CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l182_s17608CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l182_s33850CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l182_s48615CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l183_s75566CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l184_s36674CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l185_s81363CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l187_s56431CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l189_s42992CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l189_s66202CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l189_s76396CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l190_s57759CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l191_s98468CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l192_s11984CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l193_s29590CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l193_s97971CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l194_s31969CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l194_s35134CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l194_s67974CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l196_s18101CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l196_s40309CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l197_s49285CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l198_s34327CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l199_s5126CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l199_s78131CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l200_s22287CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l80_s25703CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l81_s37449CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l86_s13025CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l86_s20990CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l86_s34002CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l87_s95365CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l89_s17742CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l93_s72331CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l94_s47741CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l94_s96090CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l95_s17057CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l95_s28184CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l97_s31534CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l97_s880CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l98_s13450CXCR4_human.pdb
Trajectory/Relaxed/CXCR4_l99_s56553CXCR4_human.pdb

"\n        u = mda.Universe(file) \n        sel_u = u.select_atoms('chainID A and not type H and not name OXT')\n\n        align.alignto(u, ref, select='chainID A and not type H and not name OXT')\n        sel = u.select_atoms('all')\n        sel.write(f'{outdir}/{design}')\n"

## Detect Clashes

In [58]:
species = ['mouse', 'human']

outdir = 'Trajectory/no_membrane_clashes'
os.makedirs(outdir, exist_ok = True)

for s in species:   
    files = glob.glob(f'Trajectory/Aligned/*_{s}.pdb')
    files.sort()

    for file in files:
        design = os.path.basename(file)

        src_dir = os.path.dirname(file)
        dst_dir = outdir

        u = mda.Universe(file)
        sel = u.select_atoms('chainID B')
        com_z = sel.center_of_mass()[2]
        
        if s == 'human':
            threshold = u.select_atoms('chainID A and name CA and resid 167').center_of_mass()[2]
        else:
            threshold = u.select_atoms('chainID A and name CA and resid 172').center_of_mass()[2]

        if com_z  < threshold:
            pass
        else:
            print(f'probably no membrane clashes: ', design)
            shutil.copy(f'{src_dir}/{design}', f'{dst_dir}/{design}')

probably no membrane clashes:  CXCR4_l100_s87186CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l101_s50501CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l102_s38852CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l103_s82425CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l105_s9788CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l106_s22762CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l106_s26386CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l106_s75775CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l107_s8342CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l107_s84555CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l108_s83259CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l111_s4194CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l113_s53451CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l116_s68332CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l116_s9124CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l117_s14292CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l117_s46290CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l118_s39379CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l118_s51250CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l118_s60515CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l120_s26368CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l122_s57564CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l123_s94967CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l128_s84702CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l130_s64914CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l133_s48643CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l134_s13755CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l134_s3769CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l134_s38147CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l136_s18439CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l137_s56033CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l137_s97919CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l139_s60898CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l140_s32153CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l142_s11162CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l143_s29399CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l144_s7262CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l145_s21099CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l145_s47467CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l146_s29253CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l151_s74375CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l160_s23897CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l160_s36808CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l160_s92625CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l161_s32811CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l161_s42654CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l162_s67110CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l163_s88851CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l164_s31992CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l165_s85964CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l169_s60830CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l171_s33268CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l172_s33942CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l172_s92959CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l172_s95662CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l174_s6023CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l176_s38200CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l176_s52627CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l176_s64546CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l176_s7220CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l179_s21760CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l179_s98276CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l181_s169CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l182_s17608CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l182_s48615CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l184_s36674CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l185_s81363CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l187_s56431CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l189_s42992CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l189_s66202CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l189_s76396CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l190_s57759CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l192_s11984CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l194_s31969CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l194_s67974CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l199_s5126CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l199_s78131CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l200_s22287CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l80_s25703CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l81_s37449CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l86_s20990CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l86_s34002CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l93_s72331CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l95_s28184CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l97_s880CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l99_s56553CXCR4_mouse.pdb
probably no membrane clashes:  CXCR4_l100_s87186CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l101_s50501CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l102_s38852CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l103_s82425CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l105_s9788CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l106_s15564CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l106_s22762CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l106_s26386CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l106_s75775CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l107_s75675CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l107_s8342CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l107_s84555CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l108_s83259CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l111_s4194CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l113_s53451CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l113_s87864CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l116_s68332CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l116_s9124CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l117_s14292CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l117_s46290CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l118_s39379CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l118_s51250CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l118_s60515CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l120_s26368CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l121_s85675CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l122_s57564CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l123_s94967CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l128_s84702CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l130_s64914CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l133_s23417CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l133_s48643CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l134_s13755CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l134_s3769CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l134_s38147CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l136_s18439CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l137_s56033CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l137_s97919CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l139_s60898CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l140_s32153CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l142_s11162CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l143_s29399CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l144_s7262CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l145_s21099CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l145_s47467CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l146_s29253CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l151_s74375CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l160_s23897CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l160_s36808CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l160_s92625CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l161_s32811CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l161_s42654CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l162_s67110CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l164_s31992CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l165_s85964CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l169_s60830CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l171_s33268CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l172_s33942CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l172_s92959CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l172_s95662CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l174_s6023CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l176_s38200CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l176_s64546CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l176_s7220CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l176_s76716CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l179_s21760CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l179_s98276CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l181_s169CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l182_s17608CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l182_s48615CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l184_s36674CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l185_s81363CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l187_s56431CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l189_s42992CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l189_s66202CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l189_s76396CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l190_s57759CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l191_s98468CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l192_s11984CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l194_s31969CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l194_s67974CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l196_s40309CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l199_s5126CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l199_s78131CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l200_s22287CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l80_s25703CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l81_s37449CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l86_s20990CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l93_s72331CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l95_s28184CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l97_s880CXCR4_human.pdb
probably no membrane clashes:  CXCR4_l99_s56553CXCR4_human.pdb

In [ ]:
# Adjust trajectory CSV
species = ['mouse', 'human']

no_clashes = glob.glob('Trajectory/no_membrane_clashes/*.pdb')
no_clashes = [os.path.basename(i) for i in no_clashes if 'human' in i]
no_clashes = [i.split('CXCR4_human')[0] for i in no_clashes]

for s in species:   
    df = pd.read_csv(f'Trajectory/trajectory_CXCR4_{s}.csv')
    df = df[df["Design"].isin(no_clashes)]
    
    df.to_csv(f'Trajectory/trajectory_CXCR4_{s}_no_clashes.csv', index=False)

# MPNN Relaxed

In [47]:
df = pd.read_csv('output-CXCR4/mpnn_design_stats_hCXCR4.csv')
metrics = [i for i in df.columns if (i.startswith('Average') or i.startswith('Design'))]
df = df[metrics]

# thresholds
with open("settings_filters/default_mulitmer_target_filters.json") as f:
    thresholds = json.load(f)

# drop columns with null threshold
metrics_with_null_threshold = {
    key
    for key, value in thresholds.items()
    if isinstance(value, dict)
    and "threshold" in value
    and value["threshold"] is None
}

cols_to_drop = [col for col in df.columns if col in metrics_with_null_threshold]
df = df.drop(columns=cols_to_drop)
df_filtered = df.sort_values(by='Design')

# summarize failing metrics
fail_counts = {}

for metric, rules in thresholds.items():
    # Skip metrics not in dataframe
    if metric not in df_filtered.columns:
        continue

    threshold = rules.get("threshold")
    higher = rules.get("higher")

    values = df_filtered[metric]

    if higher:
        # FAIL if value < threshold
        fails = (values < threshold).sum()
    else:
        # FAIL if value > threshold
        fails = (values > threshold).sum()

    fail_counts[metric] = fails

fail_df = (
pd.DataFrame.from_dict(fail_counts, orient="index", columns=["n_failed"])
  .sort_values("n_failed", ascending=False)
)
fail_df['percentage'] = fail_df['n_failed'] / len(df_filtered)
fail_df

                                n_failed  percentage
Average_n_InterfaceUnsatHbonds       519    0.882653
Average_Binder_RMSD                  466    0.792517
Average_Surface_Hydrophobicity       435    0.739796
Average_Binder_pLDDT                 387    0.658163
Average_ShapeComplementarity          89    0.151361
Average_n_InterfaceHbonds             49    0.083333
Average_pLDDT                          0    0.000000
Average_pTM                            0    0.000000
Average_dG                             0    0.000000
Average_Binder_Energy_Score            0    0.000000
Average_i_pTM                          0    0.000000
Average_i_pAE                          0    0.000000
Average_dSASA                          0    0.000000
Average_n_InterfaceResidues            0    0.000000
Average_InterfaceAAs                   0    0.000000
Average_Binder_Loop%                   0    0.000000

# AF3 Prediction

In [58]:
TARGET_OPTIONS = {
    "default": "XXXX",
    "hCXCR4": "FREENANFNKIFLPTIYSIIFLTGIVGNGLVILVMGYQKKLRSMTDKYRLHLSVADLLFVITLPFWAVDAVANWYFGNFLCKAVHVIYTVNLYSSVLILAFISLDRYLAIVHATNSQRPRKLLAEKVVYVGVWIPALLLTIPDFIFANVSEADDRYICDRFYPNDLWVVVFQFQHIMVGLILPGIVILSCYCIIISKLSHSKGHQKRKALKTTVILILAFFACWLPYYIGISIDSFILLEIIKQGCEFENTVHKWISITEALAFFHCCLNPILYAFLGAKFKTSAQHALTSVSRGSSLKILSKGKR",
    "mCXCR4": "FRDENVHFNRIFLPTIYFIIFLTGIVGNGLVILVMGYQKKLRSMTDKYRLHLSVADLLFVITLPFWAVDAMADWYFGKFLCKAVHIIYTVNLYSSVLILAFISLDRYLAIVHATNSQRPRKLLAEKAVYVGVWIPALLLTIPDFIFADVSQGDISQGDDRYICDRLYPDSLWMVVFQFQHIMVGLILPGIVILSCYCIIISKLSHSKGHQKRKALKTTVILILAFFACWLPYYVGISIDSFILLGVIKQGCDFESIVHKWISITEALAFFHCCLNPILYAFLGAKFKSSAQHALNSMSRGSSLKILSKGKR"
}

len(TARGET_OPTIONS["mCXCR4"])

311

In [53]:
targets = ['hCXCR4', 'mCXCR4']

for target in targets:
    df = pd.read_csv('output-CXCR4/mpnn_seqs_new.csv')
    df = df.drop(columns=['Design'])
    df = df.rename(columns={'Name':'Design'})
    df['Target'] = target
    df.to_csv(f'output-CXCR4/mpnn_seqs_{target}.csv', index=False)

In [4]:
%%bash
jabba_dir=$( echo /mnt/DATA140To/rita/251227_duo_design_CXCR4/output-CXCR4/AF3_Prediction/ )
target_dir=$( echo /mnt/DATA8To/rita/251227_duo_design_CXCR4/output-CXCR4/AF3_Prediction )

rsync -v -am rita@jabba:$jabba_dir $target_dir

receiving file list ... done

sent 20 bytes  received 7,223,742 bytes  2,063,932.00 bytes/sec
total size is 111,236,211,524  speedup is 15,398.65

# Designs for MD

## Top scoring complexes

In [3]:
topdir = f'/Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/AF3_Prediction/output'
df = pd.read_csv(f'{topdir}/scores_CXCR4.csv')[['rank', 'design', 'human_combined_score', 'mouse_combined_score', 'avg_combined_score']]
df

,rank,design,human_combined_score,mouse_combined_score,avg_combined_score
0,1,cxcr4_l148_s81911_mpnn6,0.858374,0.839462,0.848918
1,2,cxcr4_l86_s69957_mpnn9,0.845962,0.833619,0.839790
2,3,cxcr4_l109_s23216_mpnn17,0.835576,0.839979,0.837777
3,4,cxcr4_l83_s64403_mpnn17,0.853121,0.816312,0.834716
4,5,cxcr4_l145_s394_mpnn12,0.840806,0.810907,0.825856
5,6,cxcr4_l103_s14597_mpnn4,0.843378,0.798134,0.820756
6,7,cxcr4_l86_s25899_mpnn18,0.826010,0.810852,0.818431
7,8,cxcr4_l124_s63775_mpnn16,0.794041,0.839110,0.816575
8,9,cxcr4_l102_s47749_mpnn8,0.829369,0.802196,0.815782
9,10,cxcr4_l129_s69645_mpnn4,0.827305,0.799935,0.813620
10,11,cxcr4_l121_s4673_mpnn10,0.821831,0.794620,0.808225
11,12,cxcr4_l102_s790_mpnn2,0.846745,0.768932,0.807838
12,13,cxcr4_l136_s45641_mpnn16,0.829372,0.785603,0.807488
13,14,cxcr4_l141_s54967_mpnn5,0.793768,0.803306,0.798537
14,15,cxcr4_l90_s70030_mpnn20,0.786236,0.799148,0.792692
15,16,cxcr4_l138_s85794_mpnn14,0.804159,0.775500,0.789830
16,17,cxcr4_l131_s99199_mpnn14,0.788325,0.788215,0.788270
17,18,cxcr4_l135_s63940_mpnn2,0.787474,0.783307,0.785390
18,19,cxcr4_l97_s5700_mpnn11,0.779386,0.790509,0.784947
19,20,cxcr4_l113_s46264_mpnn1,0.789472,0.775277,0.782375
20,21,cxcr4_l113_s20432_mpnn12,0.775870,0.777476,0.776673
21,22,cxcr4_l87_s59072_mpnn6,0.811576,0.739044,0.775310
22,23,cxcr4_l141_s63299_mpnn1,0.831080,0.710934,0.771007
23,24,cxcr4_l84_s18140_mpnn17,0.725645,0.815800,0.770722
24,25,cxcr4_l88_s63136_mpnn13,0.758072,0.774436,0.766254
25,26,cxcr4_l125_s65133_mpnn7,0.776766,0.753333,0.765050
26,27,cxcr4_l137_s15889_mpnn8,0.757059,0.754708,0.755883
27,28,cxcr4_l93_s13262_mpnn11,0.720553,0.782070,0.751312
28,29,cxcr4_l121_s3129_mpnn18,0.776237,0.723414,0.749826
29,30,cxcr4_l133_s32416_mpnn8,0.760718,0.738253,0.749486
30,31,cxcr4_l123_s73688_mpnn18,0.776485,0.719236,0.747860
31,32,cxcr4_l137_s57676_mpnn7,0.728794,0.765253,0.747024
32,33,cxcr4_l109_s76930_mpnn11,0.799479,0.693898,0.746688
33,34,cxcr4_l101_s22264_mpnn13,0.833652,0.659542,0.746597
34,35,cxcr4_l136_s25685_mpnn12,0.726683,0.765201,0.745942
35,36,cxcr4_l80_s1530_mpnn2,0.773577,0.710386,0.741982
36,37,cxcr4_l81_s29878_mpnn12,0.788745,0.679331,0.734038
37,38,cxcr4_l131_s25759_mpnn11,0.788347,0.679703,0.734025
38,39,cxcr4_l108_s21144_mpnn20,0.737990,0.720532,0.729261
39,40,cxcr4_l81_s78832_mpnn5,0.747449,0.709351,0.728400
40,41,cxcr4_l138_s30263_mpnn8,0.710679,0.734673,0.722676
41,42,cxcr4_l121_s4166_mpnn5,0.798247,0.635657,0.716952
42,43,cxcr4_l111_s95311_mpnn1,0.691645,0.739336,0.715491
43,44,cxcr4_l80_s39310_mpnn12,0.672848,0.754831,0.713839
44,45,cxcr4_l141_s45299_mpnn18,0.702270,0.720195,0.711232
45,46,cxcr4_l139_s29072_mpnn18,0.817587,0.591026,0.704307
46,47,cxcr4_l89_s80203_mpnn12,0.746847,0.661356,0.704102
47,48,cxcr4_l144_s20950_mpnn20,0.792145,0.608139,0.700142
48,49,cxcr4_l135_s38087_mpnn20,0.676177,0.723848,0.700012
49,50,cxcr4_l146_s85064_mpnn8,0.683476,0.714619,0.699047

## Repredict binders alone with AF3

In [24]:
def sanitize_filename(name):
    # Allow only alphanumeric characters, spaces, dashes, and underscores.
    safe = "".join(c for c in name if c.isalnum() or c in (' ', '-', '_')).rstrip()
    return safe.replace(" ", "_")

def csv_to_AF3_json(input_csv):
    folder_path = os.path.dirname(os.path.abspath(input_csv))
    
    with open(input_csv, 'r', newline='') as csv_file:
        reader = csv.DictReader(csv_file)
        
        for row in reader:
            design = row.get('Design', '').strip()
            binder = row.get('Sequence', '').strip()
            
            if design and binder:
                json_entry = {
                    "name": design,
                    "modelSeeds": [1],
                    "sequences": [
                        {
                            "protein": {
                                "id": "B",
                                "sequence": binder,
                                "unpairedMsa": "",
                                "pairedMsa": "",
                                "templates": []
                            }
                        }
                    ],
                    "dialect": "alphafold3",
                    "version": 3
                }
                
                safe_design = sanitize_filename(design)
                file_name = f"{safe_design}.json"
                outdir = os.path.join(folder_path, 'AF3_input')
                os.makedirs(outdir, exist_ok=True)
                output_path = os.path.join(outdir, file_name)
                
                with open(output_path, 'w') as json_file:
                    json.dump(json_entry, json_file, indent=2)
                print(f"JSON file saved to {output_path}")
            else:
                print(f"Skipping invalid row: {row}")

In [26]:
topdir = f'/Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/AF3_Prediction/output'
df = pd.read_csv(f'{topdir}/scores_CXCR4.csv')[['rank', 'design', 'human_sequence', 'avg_combined_score']]
df = df.rename(columns={'human_sequence' : 'Sequence', 'design':'Design'})
df['Design'] = df.apply(lambda row: f'rank{row["rank"]:02d}_{row["Design"]}', axis=1)

df = df[['Design', 'Sequence']]

topdir = '/Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict'
os.makedirs(topdir, exist_ok=True)

df.to_csv(f'{topdir}/AF3_input.csv', index=False)
csv_to_AF3_json(f'{topdir}/AF3_input.csv')

JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank01_cxcr4_l148_s81911_mpnn6.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank02_cxcr4_l86_s69957_mpnn9.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank03_cxcr4_l109_s23216_mpnn17.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank04_cxcr4_l83_s64403_mpnn17.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank05_cxcr4_l145_s394_mpnn12.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank06_cxcr4_l103_s14597_mpnn4.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank07_cxcr4_l86_s25899_mpnn18.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank08_cxcr4_l124_s63775_mpnn16.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank09_cxcr4_l102_s47749_mpnn8.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank10_cxcr4_l129_s69645_mpnn4.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank11_cxcr4_l121_s4673_mpnn10.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank12_cxcr4_l102_s790_mpnn2.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank13_cxcr4_l136_s45641_mpnn16.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank14_cxcr4_l141_s54967_mpnn5.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank15_cxcr4_l90_s70030_mpnn20.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank16_cxcr4_l138_s85794_mpnn14.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank17_cxcr4_l131_s99199_mpnn14.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank18_cxcr4_l135_s63940_mpnn2.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank19_cxcr4_l97_s5700_mpnn11.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank20_cxcr4_l113_s46264_mpnn1.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank21_cxcr4_l113_s20432_mpnn12.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank22_cxcr4_l87_s59072_mpnn6.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank23_cxcr4_l141_s63299_mpnn1.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank24_cxcr4_l84_s18140_mpnn17.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank25_cxcr4_l88_s63136_mpnn13.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank26_cxcr4_l125_s65133_mpnn7.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank27_cxcr4_l137_s15889_mpnn8.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank28_cxcr4_l93_s13262_mpnn11.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank29_cxcr4_l121_s3129_mpnn18.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank30_cxcr4_l133_s32416_mpnn8.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank31_cxcr4_l123_s73688_mpnn18.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank32_cxcr4_l137_s57676_mpnn7.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank33_cxcr4_l109_s76930_mpnn11.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank34_cxcr4_l101_s22264_mpnn13.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank35_cxcr4_l136_s25685_mpnn12.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank36_cxcr4_l80_s1530_mpnn2.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank37_cxcr4_l81_s29878_mpnn12.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank38_cxcr4_l131_s25759_mpnn11.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank39_cxcr4_l108_s21144_mpnn20.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank40_cxcr4_l81_s78832_mpnn5.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank41_cxcr4_l138_s30263_mpnn8.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank42_cxcr4_l121_s4166_mpnn5.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank43_cxcr4_l111_s95311_mpnn1.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank44_cxcr4_l80_s39310_mpnn12.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank45_cxcr4_l141_s45299_mpnn18.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank46_cxcr4_l139_s29072_mpnn18.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank47_cxcr4_l89_s80203_mpnn12.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank48_cxcr4_l144_s20950_mpnn20.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank49_cxcr4_l135_s38087_mpnn20.json
JSON file saved to /Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/AF3_input/rank50_cxcr4_l146_s85064_mpnn8.json

In [3]:
topdir = f'/Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/AF3_Prediction/output'
df = pd.read_csv(f'{topdir}/scores_CXCR4.csv')[['rank', 'design', 'human_sequence', 'avg_combined_score']]

df = df.rename(columns={'human_sequence' : 'Sequence', 'design':'Design'})
df['Design'] = df.apply(lambda row: f'rank{row["rank"]:02d}_{row["Design"]}', axis=1)

df_plddt = pd.read_csv('/Volumes/LaCie/251227_duo_design_CXCR4/output-CXCR4/af3_binder_repredict/scores_CXCR4.csv')[['design', 'ligand_plddt']]
df_plddt = df_plddt.rename(columns={'design':'Design'})

df = pd.merge(df, df_plddt, on='Design')

# filter by ligand plddt
df = df[df['ligand_plddt'] > 0.8]
df

,rank,Design,Sequence,avg_combined_score,ligand_plddt
1,2,rank02_cxcr4_l86_s69957_mpnn9,LHWGSWTLKATFINPKDGSVSSETVTVGPHRIPEEYLNKAKEENYH...,0.839790,0.805408
6,7,rank07_cxcr4_l86_s25899_mpnn18,MVVPKKKKLPAEEVVEQMRWGVSGWMSIYHAEHSLKYMIRSGEIAD...,0.818431,0.817331
8,9,rank09_cxcr4_l102_s47749_mpnn8,SSADPDFPPPLSPLETLALRARLVARMVELLSARLGREPPPYWVHE...,0.815782,0.818608
9,10,rank10_cxcr4_l129_s69645_mpnn4,KVDFKKLSEKEWLIAAMFVYSDPDTPHRINTTEAREKLAKEAGRKL...,0.813620,0.819661
12,13,rank13_cxcr4_l136_s45641_mpnn16,MMTSEELVTKMKEEMLEWFPSEEERKKVEEVFEMLGWEDPSKVKLE...,0.807488,0.855987
18,19,rank19_cxcr4_l97_s5700_mpnn11,KLSFPEYMELHEKIEKELKKDEEFVKEVVGPFLEEEERVWAEVEEK...,0.784947,0.820809
20,21,rank21_cxcr4_l113_s20432_mpnn12,DVKISKIKYIGKTFFIHHNMHYVQYYFEFIDENNKVVKKVSITVYP...,0.776673,0.828184
27,28,rank28_cxcr4_l93_s13262_mpnn11,MKVEIELEDGTIVEIELEEIPEPKNSSVYEFHQYVKELEEKYEEYK...,0.751312,0.805445
28,29,rank29_cxcr4_l121_s3129_mpnn18,HIHHFMTWERYNRHRLEELKRKIEVDGHVLSPIEQERYEQLLRLQE...,0.749826,0.823946
41,42,rank42_cxcr4_l121_s4166_mpnn5,GYMITDMVPWHPSRHHWNYPTTVEGWKEYYLKSYEELKKLVEEGYK...,0.716952,0.814962
47,48,rank48_cxcr4_l144_s20950_mpnn20,APPSVDLPVNGTAEELYEAFMGRIKTYLDAKKNGKPIPNPPEGALS...,0.700142,0.857327
48,49,rank49_cxcr4_l135_s38087_mpnn20,MKISEEEYEEELKKREEMMNTMYKIMEKNFKMLKEFMGENSEPGKA...,0.700012,0.804836

In [ ]:
df = pd.read_csv('CXCR4_duo_designs_exp.csv')
df['Design'] = df['Design'].str.replace('_model', '', regex=False)
df = df[['Design', 'human_mean_deltaG', 'mouse_mean_deltaG', 'Sequence', 'binding', 'test']]

# annotate plddt
df_plddt = pd.read_csv('af3_binder_repredict/scores_CXCR4.csv')[['design', 'duo_ligand_plddt']]
df_plddt = df_plddt.rename(columns={'design':'Design'})

df = pd.merge(df, df_plddt, on='Design')
df.to_csv('CXCR4_duo_designs_exp.csv')

,Design,human_mean_deltaG,mouse_mean_deltaG,Sequence,binding,test,duo_ligand_plddt
0,rank20_cxcr4_l113_s46264_mpnn1,-100.000000,-100.000000,GPSKPKHHHHFHGTWIIGWYDLRWQVVDKLLNPEIPDVPMTEEEKK...,both,yes,0.786823
1,rank04_cxcr4_l83_s64403_mpnn17,-100.000000,-86.100035,AEPVELNPWGFPIPNKSLVEKRCKEANVPTPDEFRNEAHKYPTGTP...,both,yes,0.763256
2,rank03_cxcr4_l109_s23216_mpnn17,-100.000000,-64.025291,MVIKYTIQTYYYYDDAGYRTMLTLRIEEVFTDGSSETTVTVSQVWT...,both,yes,0.797793
3,rank14_cxcr4_l141_s54967_mpnn5,-98.070940,-100.000000,PLEGVPEVNGEELNDVEKAVNEAIAAFFEHSRWHRSPPSGNYILFL...,both,yes,0.709825
4,rank22_cxcr4_l87_s59072_mpnn6,-82.622783,-78.042794,MNPMTSHEVWNILKENSEEYDYVNQTGQVVKAYRVAVYNKKDGSLV...,both,yes,0.645572
5,rank06_cxcr4_l103_s14597_mpnn4,-81.885811,-24.688285,MFFWMNVASYDRYMDYRMEREKYENDTTGDPETRRINLVRLGFEYI...,human,no,0.736338
6,rank29_cxcr4_l121_s3129_mpnn18,-69.806697,-25.145834,HIHHFMTWERYNRHRLEELKRKIEVDGHVLSPIEQERYEQLLRLQE...,human,no,0.823946
7,rank05_cxcr4_l145_s394_mpnn12,-69.222225,-28.972545,FHFWTPDHDITRMGPAFIDDPEKYAVGKLNEKDKAQYYASGKKIVD...,human,no,0.791381
8,rank34_cxcr4_l101_s22264_mpnn13,-68.311205,-81.365116,GPWDGLAPREVREQHVLNYAEFILGPGAVPTPEDLFEAVMRMHYWT...,both,yes,0.727355
9,rank15_cxcr4_l90_s70030_mpnn20,-51.887801,-37.382072,WFHDPHTDDGFYIKSMWRFKKYGKNPEDPQNQEVLKLKPKVEEVRE...,human,no,0.639969
10,rank02_cxcr4_l86_s69957_mpnn9,-44.720700,-41.438566,LHWGSWTLKATFINPKDGSVSSETVTVGPHRIPEEYLNKAKEENYH...,both,no,0.805408
11,rank47_cxcr4_l89_s80203_mpnn12,-38.237107,-41.332289,MKTVEELIEEAKKKIIENPELFPESHNFWSHTDAASPPWMGIGGHF...,mouse,no,0.702360
12,rank13_cxcr4_l136_s45641_mpnn16,-13.246493,9.904277,MMTSEELVTKMKEEMLEWFPSEEERKKVEEVFEMLGWEDPSKVKLE...,none,no,0.855987
13,rank21_cxcr4_l113_s20432_mpnn12,-3.056791,-64.038461,DVKISKIKYIGKTFFIHHNMHYVQYYFEFIDENNKVVKKVSITVYP...,mouse,no,0.828184
14,rank46_cxcr4_l139_s29072_mpnn18,7.307661,-9.120340,PLTPTNWDVHHEIHRMQRLEPLCEPAVFTDEEGEEVTVTVYEVKIE...,none,no,0.782324
15,rank07_cxcr4_l86_s25899_mpnn18,13.729306,-2.258070,MVVPKKKKLPAEEVVEQMRWGVSGWMSIYHAEHSLKYMIRSGEIAD...,none,no,0.817331